+incdir+../
+incdir+../spmvfiles/src
+incdir+../spmvfiles
-timescale=1ns/1ns
 tb.v
avl_slave_template.v
top.v
arbitor.v
avl_comb.v
single_adder_pipe3.v
../dut.v
../async_lsq.v
../load_queue.v
../store_queue.v
../libs/dual_clock_fifo.v
../libs/fifo_fwft.v
../libs/fifo_fwft_adapter.v
../libs/fifo.v
../libs/simple_dpram_sclk.v
../spmvfiles/src/merge_core.sv
../spmvfiles/src/page_buffer.sv
../spmvfiles/src/merge_unit.sv
../spmvfiles/src/radixsort_pb_interface.sv
../spmvfiles/src/afifo_sram.sv
../spmvfiles/src/stq_interface.sv
../spmvfiles/src/radixsort_din.sv
../spmvfiles/src/accum_blk.sv
../spmvfiles/src/arbiter.sv
../spmvfiles/src/merge_blk_fast_fifo_based.sv
../spmvfiles/src/afifo_top_slow_fast.sv
../spmvfiles/src/register_definitions.sv
../spmvfiles/src/afifo.sv
../spmvfiles/src/sfifo.sv
../spmvfiles/src/merge_stage_fast_fifo_based.sv
../spmvfiles/src/accum_stg_last.sv
../spmvfiles/src/accum_stg.sv
../spmvfiles/src/input_fifo_ctr_calc.sv
../spmvfiles/src/bitonic_sort_network.sv
../spmvfiles/src/stq_buff_unit.sv
../spmvfiles/src/adder_pipe_w_ctrl.sv
../spmvfiles/src/bitonic_ud_comparator.sv
../spmvfiles/src/merge_atom_fast_fifo_based.sv
../spmvfiles/src/comparator_2in.sv
../spmvfiles/src/merge_blk_slow_parallel_arr.sv
../spmvfiles/src/merge_blk_slow.sv
../spmvfiles/src/merge_segment_input.sv
../spmvfiles/src/merge_segment.sv
../spmvfiles/src/ptr_packed_qs.sv
../spmvfiles/src/segment_memory_input.sv
../spmvfiles/src/bram_m20k.sv
../spmvfiles/src/segment_memory.sv
../spmvfiles/src/reg_mem.sv
../spmvfiles/src/bram_mlab.sv
